version: '3'

services:
  postgres:
    image: postgres:10.23-alpine3.16
    container_name: ph_postgres_container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/var/lib/postgresql/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: ph_adminer_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
